name: Reusely Pricing Bot

on:
  workflow_dispatch:   # allows manual runs
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours (adjust if you want)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm init -y
          npm install node-fetch@2

      - name: Run push-prices.js
        run: node push-prices.js
